apiVersion: v1
kind: ConfigMap
metadata:
  name: cast-service-config
data:
  DATABASE_URI_CAST: "postgresql://cast_db_username:cast_db_password@cast-db/cast_db_dev"
  CAST_SERVICE_HOST_URL: "http://cast-service:8000/"  #8000 car service interne
