version: '3.7'

services:
  movie_service:
    build: ./movie-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./movie-service/:/app/
    ports:
      - 8001:8000
    environment:
      - DATABASE_URI=${DATABASE_URI_MOVIE}
      - CAST_SERVICE_HOST_URL=${CAST_SERVICE_HOST_URL}
    depends_on:
      - movie_db
    env_file:
      - .env  # Référence au fichier .env

  movie_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_movie:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER_MOVIE}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_MOVIE}
      - POSTGRES_DB=${POSTGRES_DB_MOVIE}
    env_file:
      - .env  # Référence au fichier .env

  cast_service:
    build: ./cast-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./cast-service/:/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URI=${DATABASE_URI_CAST}
    depends_on:
      - cast_db
    env_file:
      - .env  # Référence au fichier .env

  cast_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_cast:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER_CAST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_CAST}
      - POSTGRES_DB=${POSTGRES_DB_CAST}
    env_file:
      - .env  # Référence au fichier .env

  nginx:
    image: nginx:latest
    ports:
      - "8081:8081"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - cast_service
      - movie_service

volumes:
  postgres_data_movie:
  postgres_data_cast:
