apiVersion: v1
kind: ConfigMap
metadata:
  name: movie-service-config
  namespace: default
data:
  DATABASE_URI_MOVIE: "postgresql://movie_db_username:movie_db_password@movie-db/movie_db_dev"
  MOVIE_SERVICE_HOST_URL: "http://movie-service:8000/"  #port interne

