apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.castDb.configMapName }}
  namespace: default
data:
  POSTGRES_USER_CAST: {{ .Values.castDb.postgresUser | quote }}
  POSTGRES_PASSWORD_CAST: {{ .Values.castDb.postgresPassword | quote }}
  POSTGRES_DB_CAST: {{ .Values.castDb.postgresDb | quote }}
